import type { Metadata } from "next";
import "./globals.css";
import { Barriecito } from "next/font/google";
import { Providers } from "./providers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Coinflip",
  description: "Generated by create next app",
};

const barriecito = Barriecito({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barriecito.className} min-h-screen bg-[#004225] text-white`}>
        <Providers>
          <div className="flex min-h-screen flex-col">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
